["10.127.14.0/23"]
type = "subnet"
name = "LICSON-NET-SUBALLOC-1"

["10.127.14.0/24"]
type = "subnet"
name = "LICSON-NET-SUBALLOC-1-1"

["10.127.15.0/24"]
type = "subnet"
name = "LICSON-NET-SUBALLOC-1-2"

