["10.127.66.0/24"]
type = "subnet"
name = "POTATO-NEO-NET4-A"
description = "PotatoNet @ NeoNetwork"

["fd10:127:aa66::/48"]
type = "subnet"
name = "POTATO-NEO-NET6-A"
description = "PotatoNet @ NeoNetwork"
