["10.127.20.0/24"]
type = "subnet"
name = "Anillc Network v4"

["10.127.3.0/24"]
type = "subnet"
name = "Anillc NEO Network v4"

["fd10:127:cc::/48"]
type = "subnet"
name = "Anillc Network v6"

["fd10:127:ee::/48"]
type = "subnet"
name = "Anillc NEO Network v6"
