["10.127.234.0/24"]
type = "subnet"
name = "CainSakura-home-devices"
description = "For home devices internal network segment for testing connectivity quality, No SLA"

["10.127.235.0/24"]
type = "subnet"
name = "Icecat Global Tunnel Address (OpenVPN)"
description = "For Magicneko Explosion Network Interworking address, No SLA"

["10.127.236.0/24"]
type = "subnet"
name = "MagicNeko VPN"
description = "For Magicneko Explosion Network Interworking address, No SLA"

["fd10:127:0234::/48"]
type = "subnet"
name = "CainSakura-home-devices"
description = "For home devices internal network segment for testing connectivity quality, No SLA"
