# This is a basic workflow to help you get started with Actions

name: roa_generator

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:
    name: Generate ROA
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update -qq
          sudo apt install -y python3 git openssh-client

      - name: Run ROA script
        shell: bash
        run: .scripts/generate-roa.sh

      - name: Push to NeoCloud/NeoNetwork-ROA
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: generated
          repository: NeoCloud/NeoNetwork-ROA
