name: Generator ROA

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:
    name: Generate ROA
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: NeoCloud/NeoNetwork-ROA
          path: generated

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - run: pip install -r .scripts/requirements.txt

      - run: .scripts/generate-roa.sh

      - run: .scripts/push-to-roa.sh
        env:
          SSHPRIVKEY: ${{ secrets.KEY }}
