name: Generator ROA

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:
    name: Generate ROA
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: NeoCloud/NeoNetwork-ROA
          path: generated

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y git python3 python3-venv openssh-client

      - name: Run ROA script
        run: .scripts/generate-roa.sh

      - name: Push to NeoCloud/NeoNetwork-ROA
        env:
          SSHPRIVKEY: ${{ secrets.KEY }}
        run: .scripts/push-to-roa.sh
