name: Generator ROA

on:
  push:
    branches: [master]
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:
    name: Generate ROA
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: NeoCloud/NeoNetwork-ROA
          ssh-key: ${{ secrets.KEY }}
          path: generated

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y git python3 python3-venv openssh-client

      - name: Run ROA script
        run: .scripts/generate-roa.sh

      - name: Push to NeoCloud/NeoNetwork-ROA
        run: |
          cd generated
          git config user.name "neonet roa bot"
          git config user.email "bot@github.com"
          git commit -m "Generated at $(TZ='UTC' date +%Y%m%d-%H%M%S.%N)"
          git push
