name: Test Your PR

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Generate ROA
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - run: pip install -r .scripts/requirements.txt

      - run: .scripts/generate-roa.sh

      - run: cat generated/README.txt
