name: Test Your PR

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Generate ROA
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update -qq
          sudo apt install -y python3 python3-venv

      - name: Run ROA script
        shell: bash
        run: .scripts/generate-roa.sh
