name: Test Your PR

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Generate ROA
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3 python3-venv

      - name: Run ROA script
        run: .scripts/generate-roa.sh

      - name: Preview
        run: cat generated/README.txt
