name: Test Your PR

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Generate ROA
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v2
        with:
          repository: NeoCloud/NeoNetwork-ROA
          path: generated

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64

      - run: pip install -r .scripts/requirements.txt

      - run: .scripts/generate-roa.sh

      - run: git -C generated diff README.txt
